# Data Cleaning and Preprocessing – NorthStar Dataset

The raw dataset files are stored in the GitHub repository under: *'datasets/raw/'*

The cleaned datasets will later be saved and uploaded to: *'datasets/cleaned/'*

In [ ]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

## Importing Raw Dataset Files from GitHub

The raw NorthStar dataset files were uploaded to the GitHub repository in the 'datasets/raw/' folder. In this step, the raw Github url of each of the CSV files is directly imported to Google Colab. This way the notebook can access the original data files and you do not need to upload the files every time you run the notebook. The imported files include app events, complaints, customers, deliveries, drivers, hubs, incidents, orders, vehicles, and the data dictionary

In [ ]:
# raw github dataset links

base_url = "https://raw.githubusercontent.com/jagan-002/northstar-database-analytics-coursework/main/datasets/raw/"

app_events = pd.read_csv(base_url + "app_events.csv")
complaints = pd.read_csv(base_url + "complaints.csv")
customers = pd.read_csv(base_url + "customers.csv")
data_dictionary = pd.read_csv(base_url + "data_dictionary.csv")
deliveries = pd.read_csv(base_url + "deliveries.csv")
drivers = pd.read_csv(base_url + "drivers.csv")
hubs = pd.read_csv(base_url + "hubs.csv")
incidents = pd.read_csv(base_url + "incidents.csv")
orders = pd.read_csv(base_url + "orders.csv")
vehicles = pd.read_csv(base_url + "vehicles.csv")

print("All raw datasets imported successfully.")

All raw datasets imported successfully.

In [ ]:
# store all datasets in a dictionary for easier inspection

datasets = {
    "app_events": app_events,
    "complaints": complaints,
    "customers": customers,
    "data_dictionary": data_dictionary,
    "deliveries": deliveries,
    "drivers": drivers,
    "hubs": hubs,
    "incidents": incidents,
    "orders": orders,
    "vehicles": vehicles
}

#display the number of rows and columns in each dataset

for name, df in datasets.items():
    print(f"{name}: {df.shape[0]} rows and {df.shape[1]} columns")

app_events: 640 rows and 10 columns
complaints: 320 rows and 10 columns
customers: 650 rows and 9 columns
data_dictionary: 9 rows and 3 columns
deliveries: 950 rows and 13 columns
drivers: 170 rows and 8 columns
hubs: 8 rows and 5 columns
incidents: 280 rows and 7 columns
orders: 1250 rows and 11 columns
vehicles: 120 rows and 8 columns

## Initial Inspection of Raw Datasets

Once the raw CSV files have been imported from GitHub the next step is to inspect each dataset before cleaning. This helps in identifying the structure, data types, missing values, duplicate records and possible data quality issues

The inspection process includes:

- viewing column names
- checking the number of rows and columns
- checking data types
- checking missing values
- checking duplicate records
- previewing the first few rows of each dataset

In [ ]:
# display column names for each dataset

for name, df in datasets.items():
    print("=" * 80)
    print(f"Dataset: {name}")
    print("=" * 80)
    print("Columns:")
    print(df.columns.tolist())
    print()

================================================================================
Dataset: app_events
================================================================================
Columns:
['event_id', 'customer_id', 'order_id', 'event_timestamp', 'event_type', 'session_id', 'device_type', 'zone_context', 'api_latency_ms', 'success_flag']

================================================================================
Dataset: complaints
================================================================================
Columns:
['complaint_id', 'customer_id', 'order_id', 'complaint_type', 'channel', 'severity', 'created_at', 'status', 'resolution_days', 'compensation_amount']

================================================================================
Dataset: customers
================================================================================
Columns:
['customer_id', 'age', 'home_zone', 'customer_type', 'signup_date', 'loyalty_score', 'app_engagement_score', 'preferred_channel', 'account_status']

================================================================================
Dataset: data_dictionary
================================================================================
Columns:
['file_name', 'record_count', 'description']

================================================================================
Dataset: deliveries
================================================================================
Columns:
['delivery_id', 'order_id', 'driver_id', 'vehicle_id', 'hub_id', 'dispatch_time', 'delivery_completed_at', 'delivery_status', 'route_distance_km', 'manual_route_override_count', 'proof_of_completion_missing', 'customer_rating_post_delivery', 'fuel_or_charge_cost']

================================================================================
Dataset: drivers
================================================================================
Columns:
['driver_id', 'base_zone', 'employment_type', 'years_experience', 'training_score', 'driver_rating', 'shift_preference', 'active_flag']

================================================================================
Dataset: hubs
================================================================================
Columns:
['hub_id', 'hub_name', 'zone', 'hub_type', 'capacity_score']

================================================================================
Dataset: incidents
================================================================================
Columns:
['incident_id', 'delivery_id', 'incident_type', 'reported_at', 'severity', 'resolution_status', 'resolved_hours']

================================================================================
Dataset: orders
================================================================================
Columns:
['order_id', 'customer_id', 'service_type', 'order_created_at', 'promised_window_hours', 'pickup_zone', 'dropoff_zone', 'priority_level', 'order_value', 'booking_channel', 'special_handling_flag']

================================================================================
Dataset: vehicles
================================================================================
Columns:
['vehicle_id', 'vehicle_type', 'assigned_zone', 'commission_date', 'battery_health_pct', 'odometer_km', 'maintenance_status', 'telematics_version']

In [ ]:
# check data types for each dataset

for name, df in datasets.items():
    print("=" * 80)
    print(f"Dataset: {name}")
    print("=" * 80)
    print("Data Types:")
    print(df.dtypes)
    print()

================================================================================
Dataset: app_events
================================================================================
Data Types:
event_id           object
customer_id        object
order_id           object
event_timestamp    object
event_type         object
session_id         object
device_type        object
zone_context       object
api_latency_ms      int64
success_flag        int64
dtype: object

================================================================================
Dataset: complaints
================================================================================
Data Types:
complaint_id            object
customer_id             object
order_id                object
complaint_type          object
channel                 object
severity                object
created_at              object
status                  object
resolution_days          int64
compensation_amount    float64
dtype: object

================================================================================
Dataset: customers
================================================================================
Data Types:
customer_id              object
age                       int64
home_zone                object
customer_type            object
signup_date              object
loyalty_score           float64
app_engagement_score    float64
preferred_channel        object
account_status           object
dtype: object

================================================================================
Dataset: data_dictionary
================================================================================
Data Types:
file_name       object
record_count     int64
description     object
dtype: object

================================================================================
Dataset: deliveries
================================================================================
Data Types:
delivery_id                       object
order_id                          object
driver_id                         object
vehicle_id                        object
hub_id                            object
dispatch_time                     object
delivery_completed_at             object
delivery_status                   object
route_distance_km                float64
manual_route_override_count        int64
proof_of_completion_missing        int64
customer_rating_post_delivery    float64
fuel_or_charge_cost              float64
dtype: object

================================================================================
Dataset: drivers
================================================================================
Data Types:
driver_id            object
base_zone            object
employment_type      object
years_experience      int64
training_score      float64
driver_rating       float64
shift_preference     object
active_flag           int64
dtype: object

================================================================================
Dataset: hubs
================================================================================
Data Types:
hub_id            object
hub_name          object
zone              object
hub_type          object
capacity_score     int64
dtype: object

================================================================================
Dataset: incidents
================================================================================
Data Types:
incident_id           object
delivery_id           object
incident_type         object
reported_at           object
severity              object
resolution_status     object
resolved_hours       float64
dtype: object

================================================================================
Dataset: orders
================================================================================
Data Types:
order_id                  object
customer_id               object
service_type              object
order_created_at          object
promised_window_hours      int64
pickup_zone               object
dropoff_zone              object
priority_level            object
order_value              float64
booking_channel           object
special_handling_flag      int64
dtype: object

================================================================================
Dataset: vehicles
================================================================================
Data Types:
vehicle_id             object
vehicle_type           object
assigned_zone          object
commission_date        object
battery_health_pct    float64
odometer_km             int64
maintenance_status     object
telematics_version     object
dtype: object

In [ ]:
# check missing values and duplicate rows for each dataset

for name, df in datasets.items():
    print("=" * 80)
    print(f"Dataset: {name}")
    print("=" * 80)

    print("Missing Values:")
    print(df.isnull().sum())

    print("\nTotal Duplicate Rows:")
    print(df.duplicated().sum())

    print()

================================================================================
Dataset: app_events
================================================================================
Missing Values:
event_id             0
customer_id          0
order_id           144
event_timestamp      0
event_type           0
session_id           0
device_type          0
zone_context         0
api_latency_ms       0
success_flag         0
dtype: int64

Total Duplicate Rows:
0

================================================================================
Dataset: complaints
================================================================================
Missing Values:
complaint_id            0
customer_id             0
order_id                0
complaint_type          0
channel                 0
severity                0
created_at              0
status                  0
resolution_days         0
compensation_amount    16
dtype: int64

Total Duplicate Rows:
0

================================================================================
Dataset: customers
================================================================================
Missing Values:
customer_id              0
age                      0
home_zone                0
customer_type            0
signup_date              0
loyalty_score           20
app_engagement_score     0
preferred_channel       13
account_status           0
dtype: int64

Total Duplicate Rows:
0

================================================================================
Dataset: data_dictionary
================================================================================
Missing Values:
file_name       0
record_count    0
description     0
dtype: int64

Total Duplicate Rows:
0

================================================================================
Dataset: deliveries
================================================================================
Missing Values:
delivery_id                       0
order_id                          0
driver_id                         0
vehicle_id                        0
hub_id                            0
dispatch_time                     0
delivery_completed_at            19
delivery_status                   0
route_distance_km                 0
manual_route_override_count       0
proof_of_completion_missing       0
customer_rating_post_delivery    14
fuel_or_charge_cost               0
dtype: int64

Total Duplicate Rows:
0

================================================================================
Dataset: drivers
================================================================================
Missing Values:
driver_id           0
base_zone           0
employment_type     0
years_experience    0
training_score      7
driver_rating       0
shift_preference    0
active_flag         0
dtype: int64

Total Duplicate Rows:
0

================================================================================
Dataset: hubs
================================================================================
Missing Values:
hub_id            0
hub_name          0
zone              0
hub_type          0
capacity_score    0
dtype: int64

Total Duplicate Rows:
0

================================================================================
Dataset: incidents
================================================================================
Missing Values:
incident_id           0
delivery_id           0
incident_type         0
reported_at           0
severity              0
resolution_status     0
resolved_hours       17
dtype: int64

Total Duplicate Rows:
0

================================================================================
Dataset: orders
================================================================================
Missing Values:
order_id                  0
customer_id               0
service_type              0
order_created_at          0
promised_window_hours     0
pickup_zone               0
dropoff_zone              0
priority_level            0
order_value               0
booking_channel          25
special_handling_flag     0
dtype: int64

Total Duplicate Rows:
0

================================================================================
Dataset: vehicles
================================================================================
Missing Values:
vehicle_id            0
vehicle_type          0
assigned_zone         0
commission_date       0
battery_health_pct    4
odometer_km           0
maintenance_status    0
telematics_version    0
dtype: int64

Total Duplicate Rows:
0

In [ ]:
# preview the first five rows of each dataset

for name, df in datasets.items():
    print("=" * 80)
    print(f"Preview of {name}")
    print("=" * 80)
    display(df.head())

================================================================================
Preview of app_events
================================================================================

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag
0,AE00001,C0488,NaN,2024-08-09 03:25:00,eta_refresh,S19847,Android,north,301,1
1,AE00002,C0595,O00950,2024-02-13 22:29:00,search_route,S32766,Android,SOUTH,60,1
2,AE00003,C0494,O00170,2025-08-11 09:29:00,chat_opened,S99516,iOS,Airport,1118,1
3,AE00004,C0407,O00756,2025-08-23 17:38:00,eta_refresh,S41236,iOS,CENTRAL,442,1
4,AE00005,C0506,NaN,2024-05-29 10:33:00,search_route,S12030,iOS,north,60,1

================================================================================
Preview of complaints
================================================================================

,complaint_id,customer_id,order_id,complaint_type,channel,severity,created_at,status,resolution_days,compensation_amount
0,CP0001,C0464,O00814,AppIssue,App,High,2025-03-30 02:36:00,Open,11,23.99
1,CP0002,C0056,O00628,MissedPickup,Phone,Medium,2024-11-07 10:05:00,Open,4,21.64
2,CP0003,C0469,O00384,Delay,Chatbot,High,2024-01-02 15:47:00,Open,16,26.41
3,CP0004,C0631,O00406,Delay,App,Medium,2025-01-14 13:07:00,AwaitingCustomer,7,23.44
4,CP0005,C0535,O00154,Delay,Email,Medium,2024-08-31 05:56:00,Resolved,1,16.18

================================================================================
Preview of customers
================================================================================

,customer_id,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status
0,C0001,26,North,SME,2024-11-27 04:25:00,44.9,69.2,App,Active
1,C0002,61,AIRPORT,Consumer,2025-10-28 01:04:00,55.4,66.6,App,Active
2,C0003,66,East,Consumer,2025-07-02 03:23:00,75.9,33.8,NaN,Active
3,C0004,75,CENTRAL,Consumer,2025-08-19 01:58:00,32.5,33.0,App,Active
4,C0005,26,Riverside,Consumer,2025-06-03 06:02:00,55.9,100.0,Web,Active

================================================================================
Preview of data_dictionary
================================================================================

,file_name,record_count,description
0,hubs.csv,8,Operational hubs and control points
1,customers.csv,650,Customer master data with engagement and loyal...
2,drivers.csv,170,Driver workforce data with training and rating...
3,vehicles.csv,120,Fleet asset data including battery and mainten...
4,orders.csv,1250,Service orders across mobility and logistics o...

================================================================================
Preview of deliveries
================================================================================

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2024-06-19 09:05:59.904311,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,2025-06-02 21:45:32.366770,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,2024-03-09 23:30:08.103702,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,2025-09-21 15:45:34.131056,OnTime,14.52,1,0,4.18,9.22

================================================================================
Preview of drivers
================================================================================

,driver_id,base_zone,employment_type,years_experience,training_score,driver_rating,shift_preference,active_flag
0,D001,AIRPORT,FullTime,8,67.8,3.54,Morning,1
1,D002,Central,FullTime,4,42.4,3.94,Evening,1
2,D003,AIRPORT,FullTime,11,96.5,5.00,Evening,1
3,D004,Airport,PartTime,13,88.9,4.75,Morning,1
4,D005,north,FullTime,3,69.7,4.14,Morning,1

================================================================================
Preview of hubs
================================================================================

  hub_id        hub_name     zone   hub_type  capacity_score
0    H01  North Exchange    North   Dispatch              82
1    H02      South Link    South   Dispatch              78
2    H03       East Dock     East  Warehouse              74
3    H04       West Gate     West   Dispatch              69
4    H05    Central Core  Central    Control              88

================================================================================
Preview of incidents
================================================================================

,incident_id,delivery_id,incident_type,reported_at,severity,resolution_status,resolved_hours
0,I0001,DL00221,BatteryAlert,2024-03-11 23:46:00,Medium,Escalated,12.3
1,I0002,DL00578,BatteryAlert,2024-02-21 10:56:00,Low,Open,9.6
2,I0003,DL00175,TemperatureIssue,2025-04-17 23:22:00,Medium,Open,22.0
3,I0004,DL00417,ProofMissing,2025-02-09 00:16:00,Medium,Closed,9.8
4,I0005,DL00897,RouteDeviation,2025-01-04 02:49:00,Low,Open,13.0

================================================================================
Preview of orders
================================================================================

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,AIRPORT,Low,109.30,App,0
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,AIRPORT,High,33.50,Phone,0
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,RiverSide,North,Medium,10.04,App,1
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,SOUTH,Low,125.58,Phone,0

================================================================================
Preview of vehicles
================================================================================

,vehicle_id,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version
0,V001,EV,North,2024-12-28 23:48:00,71.8,56928,Active,v2.2
1,V002,EV,AIRPORT,2024-04-21 16:14:00,67.9,159368,InRepair,v2.2
2,V003,CargoVan,north,2025-11-24 23:59:00,91.7,219359,Active,v2.1
3,V004,Hybrid,RiverSide,2024-06-07 13:21:00,NaN,36310,Active,v2.2
4,V005,CargoVan,West,2025-11-15 11:08:00,58.6,146638,Active,v2.2

## Cleaning and Standardising Column Names

The first step in cleaning after inspecting the raw data sets is to standardise the column names. Having consistent column names makes it easier to write code, merge datasets, run queries, and avoid errors due to spaces, capital letters, or special characters. In this step, all column names are converted to lower case, extra spaces are removed and spaces are replaced by underscores

In [ ]:
# function to clean column names

def clean_column_names(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
        .str.replace("/", "_", regex=False)
    )
    return df

# apply column name cleaning to all datasets

app_events_clean = clean_column_names(app_events)
complaints_clean = clean_column_names(complaints)
customers_clean = clean_column_names(customers)
deliveries_clean = clean_column_names(deliveries)
drivers_clean = clean_column_names(drivers)
hubs_clean = clean_column_names(hubs)
incidents_clean = clean_column_names(incidents)
orders_clean = clean_column_names(orders)
vehicles_clean = clean_column_names(vehicles)

print("Column names cleaned successfully.")

Column names cleaned successfully.

In [ ]:
# store cleaned datasets in a dictionary

cleaned_datasets = {
    "app_events_clean": app_events_clean,
    "complaints_clean": complaints_clean,
    "customers_clean": customers_clean,
    "deliveries_clean": deliveries_clean,
    "drivers_clean": drivers_clean,
    "hubs_clean": hubs_clean,
    "incidents_clean": incidents_clean,
    "orders_clean": orders_clean,
    "vehicles_clean": vehicles_clean
}

# display cleaned column names

for name, df in cleaned_datasets.items():
    print("=" * 80)
    print(f"Dataset: {name}")
    print("=" * 80)
    print(df.columns.tolist())
    print()

================================================================================
Dataset: app_events_clean
================================================================================
['event_id', 'customer_id', 'order_id', 'event_timestamp', 'event_type', 'session_id', 'device_type', 'zone_context', 'api_latency_ms', 'success_flag']

================================================================================
Dataset: complaints_clean
================================================================================
['complaint_id', 'customer_id', 'order_id', 'complaint_type', 'channel', 'severity', 'created_at', 'status', 'resolution_days', 'compensation_amount']

================================================================================
Dataset: customers_clean
================================================================================
['customer_id', 'age', 'home_zone', 'customer_type', 'signup_date', 'loyalty_score', 'app_engagement_score', 'preferred_channel', 'account_status']

================================================================================
Dataset: deliveries_clean
================================================================================
['delivery_id', 'order_id', 'driver_id', 'vehicle_id', 'hub_id', 'dispatch_time', 'delivery_completed_at', 'delivery_status', 'route_distance_km', 'manual_route_override_count', 'proof_of_completion_missing', 'customer_rating_post_delivery', 'fuel_or_charge_cost']

================================================================================
Dataset: drivers_clean
================================================================================
['driver_id', 'base_zone', 'employment_type', 'years_experience', 'training_score', 'driver_rating', 'shift_preference', 'active_flag']

================================================================================
Dataset: hubs_clean
================================================================================
['hub_id', 'hub_name', 'zone', 'hub_type', 'capacity_score']

================================================================================
Dataset: incidents_clean
================================================================================
['incident_id', 'delivery_id', 'incident_type', 'reported_at', 'severity', 'resolution_status', 'resolved_hours']

================================================================================
Dataset: orders_clean
================================================================================
['order_id', 'customer_id', 'service_type', 'order_created_at', 'promised_window_hours', 'pickup_zone', 'dropoff_zone', 'priority_level', 'order_value', 'booking_channel', 'special_handling_flag']

================================================================================
Dataset: vehicles_clean
================================================================================
['vehicle_id', 'vehicle_type', 'assigned_zone', 'commission_date', 'battery_health_pct', 'odometer_km', 'maintenance_status', 'telematics_version']

## Cleaning Date and Time Columns

Several of the NorthStar datasets have date/time columns. These columns need to be converted from text format into proper datetime format for time-based analysis. This step is important for later analysis where we need to do calculations such as delivery duration, complaint trends over time, incident resolution time, customer signup patterns, and app event activity. Using the right date and time format for your columns will help you to get better accuracy in your analysis

In [ ]:
# convert date and time columns into datetime format

app_events_clean["event_timestamp"] = pd.to_datetime(app_events_clean["event_timestamp"], errors="coerce")

complaints_clean["created_at"] = pd.to_datetime(complaints_clean["created_at"], errors="coerce")

customers_clean["signup_date"] = pd.to_datetime(customers_clean["signup_date"], errors="coerce")

deliveries_clean["dispatch_time"] = pd.to_datetime(deliveries_clean["dispatch_time"], errors="coerce")
deliveries_clean["delivery_completed_at"] = pd.to_datetime(deliveries_clean["delivery_completed_at"], errors="coerce")

incidents_clean["reported_at"] = pd.to_datetime(incidents_clean["reported_at"], errors="coerce")

orders_clean["order_created_at"] = pd.to_datetime(orders_clean["order_created_at"], errors="coerce")

vehicles_clean["commission_date"] = pd.to_datetime(vehicles_clean["commission_date"], errors="coerce")

print("Date and time columns converted successfully.")

Date and time columns converted successfully.

In [ ]:
# check converted date/time columns

datetime_checks = {
    "app_events_clean": app_events_clean[["event_timestamp"]],
    "complaints_clean": complaints_clean[["created_at"]],
    "customers_clean": customers_clean[["signup_date"]],
    "deliveries_clean": deliveries_clean[["dispatch_time", "delivery_completed_at"]],
    "incidents_clean": incidents_clean[["reported_at"]],
    "orders_clean": orders_clean[["order_created_at"]],
    "vehicles_clean": vehicles_clean[["commission_date"]]
}

for name, df in datetime_checks.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    print(df.dtypes)
    display(df.head())

================================================================================
app_events_clean
================================================================================
event_timestamp    datetime64[ns]
dtype: object

      event_timestamp
0 2024-08-09 03:25:00
1 2024-02-13 22:29:00
2 2025-08-11 09:29:00
3 2025-08-23 17:38:00
4 2024-05-29 10:33:00

================================================================================
complaints_clean
================================================================================
created_at    datetime64[ns]
dtype: object

           created_at
0 2025-03-30 02:36:00
1 2024-11-07 10:05:00
2 2024-01-02 15:47:00
3 2025-01-14 13:07:00
4 2024-08-31 05:56:00

================================================================================
customers_clean
================================================================================
signup_date    datetime64[ns]
dtype: object

          signup_date
0 2024-11-27 04:25:00
1 2025-10-28 01:04:00
2 2025-07-02 03:23:00
3 2025-08-19 01:58:00
4 2025-06-03 06:02:00

================================================================================
deliveries_clean
================================================================================
dispatch_time            datetime64[ns]
delivery_completed_at    datetime64[ns]
dtype: object

        dispatch_time      delivery_completed_at
0 2024-06-18 10:57:00 2024-06-19 09:05:59.904311
1 2025-01-11 18:45:00 2025-01-11 17:39:00.000000
2 2025-06-02 20:39:00 2025-06-02 21:45:32.366770
3 2024-03-08 23:31:00 2024-03-09 23:30:08.103702
4 2025-09-21 11:43:00 2025-09-21 15:45:34.131056

================================================================================
incidents_clean
================================================================================
reported_at    datetime64[ns]
dtype: object

          reported_at
0 2024-03-11 23:46:00
1 2024-02-21 10:56:00
2 2025-04-17 23:22:00
3 2025-02-09 00:16:00
4 2025-01-04 02:49:00

================================================================================
orders_clean
================================================================================
order_created_at    datetime64[ns]
dtype: object

     order_created_at
0 2024-08-20 14:43:00
1 2024-05-14 22:16:00
2 2025-09-02 14:37:00
3 2025-01-11 17:15:00
4 2025-02-17 19:32:00

================================================================================
vehicles_clean
================================================================================
commission_date    datetime64[ns]
dtype: object

      commission_date
0 2024-12-28 23:48:00
1 2024-04-21 16:14:00
2 2025-11-24 23:59:00
3 2024-06-07 13:21:00
4 2025-11-15 11:08:00

## Standardising Text and Categorical Values

The next step after transforming date and time columns is to normalise text-based categorical values. Some columns have values like zones, service types, statuses, channels, incident types, vehicle categories etc. If these values are entered with inconsistent capitalisation or spacing, they can have an impact on grouping, filtering, visualisation and subsequent database queries. This step cleans text values by removing extra spaces and making categorical values consistently Title Case. This improves the reliability of subsequent analysis including complaints by zone, delivery status by hub, incidents by severity and orders by service type

In [ ]:
# function to standardise text values in object/string columns

def standardise_text_columns(df):
    df = df.copy()

    text_columns = df.select_dtypes(include=["object"]).columns

    for col in text_columns:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace("nan", np.nan)

    return df

# apply text standardisation to all cleaned datasets

app_events_clean = standardise_text_columns(app_events_clean)
complaints_clean = standardise_text_columns(complaints_clean)
customers_clean = standardise_text_columns(customers_clean)
deliveries_clean = standardise_text_columns(deliveries_clean)
drivers_clean = standardise_text_columns(drivers_clean)
hubs_clean = standardise_text_columns(hubs_clean)
incidents_clean = standardise_text_columns(incidents_clean)
orders_clean = standardise_text_columns(orders_clean)
vehicles_clean = standardise_text_columns(vehicles_clean)

print("Text columns standardised successfully.")

Text columns standardised successfully.

In [ ]:
# standardise zone-related columns

zone_columns = [
    (app_events_clean, "zone_context"),
    (customers_clean, "home_zone"),
    (drivers_clean, "base_zone"),
    (hubs_clean, "zone"),
    (orders_clean, "pickup_zone"),
    (orders_clean, "dropoff_zone"),
    (vehicles_clean, "assigned_zone")
]

for df, col in zone_columns:
    if col in df.columns:
        df[col] = df[col].str.title()

print("Zone-related columns standardised successfully.")

Zone-related columns standardised successfully.

In [ ]:
# check unique values in key categorical columns after standardisation

categorical_checks = {
    "app_events - zone_context": app_events_clean["zone_context"].unique(),
    "complaints - complaint_type": complaints_clean["complaint_type"].unique(),
    "complaints - severity": complaints_clean["severity"].unique(),
    "complaints - status": complaints_clean["status"].unique(),
    "customers - home_zone": customers_clean["home_zone"].unique(),
    "customers - customer_type": customers_clean["customer_type"].unique(),
    "deliveries - delivery_status": deliveries_clean["delivery_status"].unique(),
    "drivers - base_zone": drivers_clean["base_zone"].unique(),
    "hubs - zone": hubs_clean["zone"].unique(),
    "incidents - incident_type": incidents_clean["incident_type"].unique(),
    "incidents - severity": incidents_clean["severity"].unique(),
    "orders - service_type": orders_clean["service_type"].unique(),
    "orders - pickup_zone": orders_clean["pickup_zone"].unique(),
    "orders - dropoff_zone": orders_clean["dropoff_zone"].unique(),
    "vehicles - vehicle_type": vehicles_clean["vehicle_type"].unique(),
    "vehicles - maintenance_status": vehicles_clean["maintenance_status"].unique()
}

for name, values in categorical_checks.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    print(values)
    print()

================================================================================
app_events - zone_context
================================================================================
['North' 'South' 'Airport' 'Central' 'West' 'Ctr' 'Riverside' 'East']

================================================================================
complaints - complaint_type
================================================================================
['AppIssue' 'MissedPickup' 'Delay' 'DriverBehaviour' 'Billing' 'Damage'
 'SupportExperience']

================================================================================
complaints - severity
================================================================================
['High' 'Medium' 'Low']

================================================================================
complaints - status
================================================================================
['Open' 'AwaitingCustomer' 'Resolved' 'Escalated']

================================================================================
customers - home_zone
================================================================================
['North' 'Airport' 'East' 'Central' 'Riverside' 'West' 'South' 'Ctr']

================================================================================
customers - customer_type
================================================================================
['SME' 'Consumer' 'Enterprise']

================================================================================
deliveries - delivery_status
================================================================================
['Failed' 'OnTime' 'Delayed']

================================================================================
drivers - base_zone
================================================================================
['Airport' 'Central' 'North' 'South' 'West' 'East' 'Riverside' 'Ctr']

================================================================================
hubs - zone
================================================================================
['North' 'South' 'East' 'West' 'Central' 'Airport' 'Riverside']

================================================================================
incidents - incident_type
================================================================================
['BatteryAlert' 'TemperatureIssue' 'ProofMissing' 'RouteDeviation'
 'CustomerNoShow' 'AppSyncError' 'VehicleFault' 'SafetyNearMiss']

================================================================================
incidents - severity
================================================================================
['Medium' 'Low' 'High' 'Critical']

================================================================================
orders - service_type
================================================================================
['Passenger' 'Parcel' 'Retail' 'Business' 'Medical']

================================================================================
orders - pickup_zone
================================================================================
['Airport' 'North' 'West' 'Riverside' 'Central' 'South' 'East' 'Ctr']

================================================================================
orders - dropoff_zone
================================================================================
['South' 'Airport' 'North' 'East' 'Riverside' 'Central' 'Ctr' 'West']

================================================================================
vehicles - vehicle_type
================================================================================
['EV' 'CargoVan' 'Hybrid' 'Diesel']

================================================================================
vehicles - maintenance_status
================================================================================
['Active' 'InRepair' 'Scheduled']

## Checking and Handling Missing Values

Analysis reliability may be impacted by missing values, particularly when computing averages, totals, rates, delivery times, complaint trends, and operational performance metrics. All NorthStar datasets are examined for missing values prior to cleaning. This step's goal is to locate missing values and handle them properly based on each column's meaning rather than removing data carelessly. While some missing data might be fine, others might need to be filled in, marked, or eliminated if they have an impact on important analysis

In [ ]:
# update cleaned datasets dictionary after previous cleaning steps

cleaned_datasets = {
    "app_events_clean": app_events_clean,
    "complaints_clean": complaints_clean,
    "customers_clean": customers_clean,
    "deliveries_clean": deliveries_clean,
    "drivers_clean": drivers_clean,
    "hubs_clean": hubs_clean,
    "incidents_clean": incidents_clean,
    "orders_clean": orders_clean,
    "vehicles_clean": vehicles_clean
}

# check missing values in each cleaned dataset

for name, df in cleaned_datasets.items():
    print("=" * 80)
    print(f"Missing values in {name}")
    print("=" * 80)

    missing_values = df.isnull().sum()
    missing_values = missing_values[missing_values > 0]

    if missing_values.empty:
        print("No missing values found.")
    else:
        print(missing_values)

    print()

================================================================================
Missing values in app_events_clean
================================================================================
order_id    144
dtype: int64

================================================================================
Missing values in complaints_clean
================================================================================
compensation_amount    16
dtype: int64

================================================================================
Missing values in customers_clean
================================================================================
loyalty_score        20
preferred_channel    13
dtype: int64

================================================================================
Missing values in deliveries_clean
================================================================================
delivery_completed_at            19
customer_rating_post_delivery    14
dtype: int64

================================================================================
Missing values in drivers_clean
================================================================================
training_score    7
dtype: int64

================================================================================
Missing values in hubs_clean
================================================================================
No missing values found.

================================================================================
Missing values in incidents_clean
================================================================================
resolved_hours    17
dtype: int64

================================================================================
Missing values in orders_clean
================================================================================
booking_channel    25
dtype: int64

================================================================================
Missing values in vehicles_clean
================================================================================
battery_health_pct    4
dtype: int64

In [ ]:
# calculate missing value percentage for each dataset

for name, df in cleaned_datasets.items():
    print("=" * 80)
    print(f"Missing value percentage in {name}")
    print("=" * 80)

    missing_percent = (df.isnull().sum() / len(df)) * 100
    missing_percent = missing_percent[missing_percent > 0].round(2)

    if missing_percent.empty:
        print("No missing values found.")
    else:
        print(missing_percent)

    print()

================================================================================
Missing value percentage in app_events_clean
================================================================================
order_id    22.5
dtype: float64

================================================================================
Missing value percentage in complaints_clean
================================================================================
compensation_amount    5.0
dtype: float64

================================================================================
Missing value percentage in customers_clean
================================================================================
loyalty_score        3.08
preferred_channel    2.00
dtype: float64

================================================================================
Missing value percentage in deliveries_clean
================================================================================
delivery_completed_at            2.00
customer_rating_post_delivery    1.47
dtype: float64

================================================================================
Missing value percentage in drivers_clean
================================================================================
training_score    4.12
dtype: float64

================================================================================
Missing value percentage in hubs_clean
================================================================================
No missing values found.

================================================================================
Missing value percentage in incidents_clean
================================================================================
resolved_hours    6.07
dtype: float64

================================================================================
Missing value percentage in orders_clean
================================================================================
booking_channel    2.0
dtype: float64

================================================================================
Missing value percentage in vehicles_clean
================================================================================
battery_health_pct    3.33
dtype: float64

### Missing Value Handling Strategy

The type and significance of each column determined the missing value handling. Because they are necessary for connecting datasets, significant identifier columns were kept. 'Unknown' was used to substitute missing values in categorical columns where the lack of information still had analytical relevance. Since the median is less impacted by extreme numbers than the mean, it was used to fill in missing values for numerical columns when suitable. Since replacing missing timestamps with false dates could result in time-based analysis that is misleading, date and time columns were not force-filled

In [ ]:
# function to handle missing values carefully

def handle_missing_values(df):
    df = df.copy()

    for col in df.columns:
        if df[col].dtype == "object":
            df[col] = df[col].fillna("Unknown")
        elif pd.api.types.is_numeric_dtype(df[col]):
            if df[col].isnull().sum() > 0:
                df[col] = df[col].fillna(df[col].median())

    return df

# apply missing value handling to all cleaned datasets

app_events_clean = handle_missing_values(app_events_clean)
complaints_clean = handle_missing_values(complaints_clean)
customers_clean = handle_missing_values(customers_clean)
deliveries_clean = handle_missing_values(deliveries_clean)
drivers_clean = handle_missing_values(drivers_clean)
hubs_clean = handle_missing_values(hubs_clean)
incidents_clean = handle_missing_values(incidents_clean)
orders_clean = handle_missing_values(orders_clean)
vehicles_clean = handle_missing_values(vehicles_clean)

print("Missing values handled successfully.")

Missing values handled successfully.

In [ ]:
# verify remaining missing values after handling

cleaned_datasets = {
    "app_events_clean": app_events_clean,
    "complaints_clean": complaints_clean,
    "customers_clean": customers_clean,
    "deliveries_clean": deliveries_clean,
    "drivers_clean": drivers_clean,
    "hubs_clean": hubs_clean,
    "incidents_clean": incidents_clean,
    "orders_clean": orders_clean,
    "vehicles_clean": vehicles_clean
}

for name, df in cleaned_datasets.items():
    print("=" * 80)
    print(f"Remaining missing values in {name}")
    print("=" * 80)

    remaining_missing = df.isnull().sum()
    remaining_missing = remaining_missing[remaining_missing > 0]

    if remaining_missing.empty:
        print("No remaining missing values.")
    else:
        print(remaining_missing)

    print()

================================================================================
Remaining missing values in app_events_clean
================================================================================
No remaining missing values.

================================================================================
Remaining missing values in complaints_clean
================================================================================
No remaining missing values.

================================================================================
Remaining missing values in customers_clean
================================================================================
No remaining missing values.

================================================================================
Remaining missing values in deliveries_clean
================================================================================
delivery_completed_at    19
dtype: int64

================================================================================
Remaining missing values in drivers_clean
================================================================================
No remaining missing values.

================================================================================
Remaining missing values in hubs_clean
================================================================================
No remaining missing values.

================================================================================
Remaining missing values in incidents_clean
================================================================================
No remaining missing values.

================================================================================
Remaining missing values in orders_clean
================================================================================
No remaining missing values.

================================================================================
Remaining missing values in vehicles_clean
================================================================================
No remaining missing values.

## Checking and Removing Duplicate Records

By incorrectly boosting counts, totals, averages, and summary statistics, duplicate records can compromise analysis accuracy. Each cleaned dataset is examined for duplicate rows after managing missing values. To guarantee that subsequent research is based on distinct records, duplicate rows are eliminated when they are discovered. This phase enhances the dependability of MongoDB data insertion, Python analysis, and SQL queries.

In [ ]:
# check duplicate records before removal

for name, df in cleaned_datasets.items():
    print("=" * 80)
    print(f"Duplicate rows before removal in {name}")
    print("=" * 80)
    print(df.duplicated().sum())
    print()

================================================================================
Duplicate rows before removal in app_events_clean
================================================================================
0

================================================================================
Duplicate rows before removal in complaints_clean
================================================================================
0

================================================================================
Duplicate rows before removal in customers_clean
================================================================================
0

================================================================================
Duplicate rows before removal in deliveries_clean
================================================================================
0

================================================================================
Duplicate rows before removal in drivers_clean
================================================================================
0

================================================================================
Duplicate rows before removal in hubs_clean
================================================================================
0

================================================================================
Duplicate rows before removal in incidents_clean
================================================================================
0

================================================================================
Duplicate rows before removal in orders_clean
================================================================================
0

================================================================================
Duplicate rows before removal in vehicles_clean
================================================================================
0

In [ ]:
# remove duplicate rows from all cleaned datasets

app_events_clean = app_events_clean.drop_duplicates()
complaints_clean = complaints_clean.drop_duplicates()
customers_clean = customers_clean.drop_duplicates()
deliveries_clean = deliveries_clean.drop_duplicates()
drivers_clean = drivers_clean.drop_duplicates()
hubs_clean = hubs_clean.drop_duplicates()
incidents_clean = incidents_clean.drop_duplicates()
orders_clean = orders_clean.drop_duplicates()
vehicles_clean = vehicles_clean.drop_duplicates()

print("Duplicate records removed successfully.")

Duplicate records removed successfully.

In [ ]:
# verify duplicate records after removal

cleaned_datasets = {
    "app_events_clean": app_events_clean,
    "complaints_clean": complaints_clean,
    "customers_clean": customers_clean,
    "deliveries_clean": deliveries_clean,
    "drivers_clean": drivers_clean,
    "hubs_clean": hubs_clean,
    "incidents_clean": incidents_clean,
    "orders_clean": orders_clean,
    "vehicles_clean": vehicles_clean
}

for name, df in cleaned_datasets.items():
    print("=" * 80)
    print(f"Duplicate rows after removal in {name}")
    print("=" * 80)
    print(df.duplicated().sum())
    print()

================================================================================
Duplicate rows after removal in app_events_clean
================================================================================
0

================================================================================
Duplicate rows after removal in complaints_clean
================================================================================
0

================================================================================
Duplicate rows after removal in customers_clean
================================================================================
0

================================================================================
Duplicate rows after removal in deliveries_clean
================================================================================
0

================================================================================
Duplicate rows after removal in drivers_clean
================================================================================
0

================================================================================
Duplicate rows after removal in hubs_clean
================================================================================
0

================================================================================
Duplicate rows after removal in incidents_clean
================================================================================
0

================================================================================
Duplicate rows after removal in orders_clean
================================================================================
0

================================================================================
Duplicate rows after removal in vehicles_clean
================================================================================
0

## Checking Key ID Columns and Dataset Relationships

The NorthStar dataset consists of multiple connected files. It's crucial to confirm that key identifier columns can be used to properly connect the data before building integrated datasets. Customers related to orders, orders linked to deliveries and complaints, deliveries linked to drivers, vehicles, hubs, and incidents are all examples of common linkages that are checked in this stage. These verifications help in ensuring that the datasets can be safely combined for additional research

In [ ]:
# function to check whether foreign key values exist in the related parent table

def check_relationship(child_df, child_key, parent_df, parent_key, relationship_name):
    total_records = len(child_df)
    matched_records = child_df[child_key].isin(parent_df[parent_key]).sum()
    unmatched_records = total_records - matched_records

    print("=" * 80)
    print(relationship_name)
    print("=" * 80)
    print(f"Total records checked: {total_records}")
    print(f"Matched records: {matched_records}")
    print(f"Unmatched records: {unmatched_records}")
    print(f"Match percentage: {(matched_records / total_records) * 100:.2f}%")
    print()

# relationship checks

check_relationship(orders_clean, "customer_id", customers_clean, "customer_id", "Orders linked to Customers")
check_relationship(complaints_clean, "customer_id", customers_clean, "customer_id", "Complaints linked to Customers")
check_relationship(complaints_clean, "order_id", orders_clean, "order_id", "Complaints linked to Orders")
check_relationship(deliveries_clean, "order_id", orders_clean, "order_id", "Deliveries linked to Orders")
check_relationship(deliveries_clean, "driver_id", drivers_clean, "driver_id", "Deliveries linked to Drivers")
check_relationship(deliveries_clean, "vehicle_id", vehicles_clean, "vehicle_id", "Deliveries linked to Vehicles")
check_relationship(deliveries_clean, "hub_id", hubs_clean, "hub_id", "Deliveries linked to Hubs")
check_relationship(incidents_clean, "delivery_id", deliveries_clean, "delivery_id", "Incidents linked to Deliveries")
check_relationship(app_events_clean, "customer_id", customers_clean, "customer_id", "App Events linked to Customers")
check_relationship(app_events_clean, "order_id", orders_clean, "order_id", "App Events linked to Orders")

================================================================================
Orders linked to Customers
================================================================================
Total records checked: 1250
Matched records: 1250
Unmatched records: 0
Match percentage: 100.00%

================================================================================
Complaints linked to Customers
================================================================================
Total records checked: 320
Matched records: 320
Unmatched records: 0
Match percentage: 100.00%

================================================================================
Complaints linked to Orders
================================================================================
Total records checked: 320
Matched records: 320
Unmatched records: 0
Match percentage: 100.00%

================================================================================
Deliveries linked to Orders
================================================================================
Total records checked: 950
Matched records: 950
Unmatched records: 0
Match percentage: 100.00%

================================================================================
Deliveries linked to Drivers
================================================================================
Total records checked: 950
Matched records: 950
Unmatched records: 0
Match percentage: 100.00%

================================================================================
Deliveries linked to Vehicles
================================================================================
Total records checked: 950
Matched records: 950
Unmatched records: 0
Match percentage: 100.00%

================================================================================
Deliveries linked to Hubs
================================================================================
Total records checked: 950
Matched records: 950
Unmatched records: 0
Match percentage: 100.00%

================================================================================
Incidents linked to Deliveries
================================================================================
Total records checked: 280
Matched records: 280
Unmatched records: 0
Match percentage: 100.00%

================================================================================
App Events linked to Customers
================================================================================
Total records checked: 640
Matched records: 640
Unmatched records: 0
Match percentage: 100.00%

================================================================================
App Events linked to Orders
================================================================================
Total records checked: 640
Matched records: 496
Unmatched records: 144
Match percentage: 77.50%

## Creating Derived and Integrated Datasets

Following the cleaning of the individual files, extra processed datasets are generated to help in further analysis. These derived datasets integrate relevant NorthStar records to provide more helpful analytical views. The linked datasets are used to assess customer complaints, delivery performance, hub efficiency, driver problems, and overall operational performance across the organization

In [ ]:
# create an integrated orders and deliveries dataset

integrated_orders_deliveries = orders_clean.merge(
    deliveries_clean,
    on="order_id",
    how="left"
)

print("integrated_orders_deliveries created successfully.")
print(integrated_orders_deliveries.shape)
display(integrated_orders_deliveries.head())

integrated_orders_deliveries created successfully.
(1250, 23)

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag,delivery_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0,DL00937,D047,V090,H01,2024-08-20 16:29:00,2024-08-20 18:52:56.172161,OnTime,26.65,2.0,0.0,4.29,15.82
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,Airport,Low,109.30,App,0,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,Airport,High,33.50,Phone,0,DL00925,D041,V100,H02,2025-09-02 16:59:00,2025-09-03 01:50:39.644673,Delayed,13.04,2.0,0.0,3.70,13.16
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,Riverside,North,Medium,10.04,App,1,DL00002,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1.0,0.0,5.00,13.41
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,South,Low,125.58,Phone,0,DL00671,D054,V073,H03,2025-02-17 20:23:00,2025-02-18 08:05:00.047082,OnTime,16.01,1.0,0.0,4.38,13.53

In [ ]:
# create customer complaint summary dataset

customer_complaint_summary = complaints_clean.groupby("customer_id").agg(
    total_complaints=("complaint_id", "count"),
    average_resolution_days=("resolution_days", "mean"),
    total_compensation=("compensation_amount", "sum")
).reset_index()

print("customer_complaint_summary created successfully.")
print(customer_complaint_summary.shape)
display(customer_complaint_summary.head())

customer_complaint_summary created successfully.
(233, 4)

  customer_id  total_complaints  average_resolution_days  total_compensation
0       C0001                 2                     13.0               43.90
1       C0004                 2                     12.0               35.58
2       C0010                 1                     10.0               15.73
3       C0012                 2                     11.5               34.66
4       C0013                 1                     16.0                9.98

In [ ]:
# create driver incident summary dataset

driver_incident_data = deliveries_clean.merge(
    incidents_clean,
    on="delivery_id",
    how="left"
)

driver_incident_summary = driver_incident_data.groupby("driver_id").agg(
    total_deliveries=("delivery_id", "count"),
    total_incidents=("incident_id", "count"),
    average_resolved_hours=("resolved_hours", "mean")
).reset_index()

driver_incident_summary["incident_rate"] = (
    driver_incident_summary["total_incidents"] / driver_incident_summary["total_deliveries"]
).round(3)

print("driver_incident_summary created successfully.")
print(driver_incident_summary.shape)
display(driver_incident_summary.head())

driver_incident_summary created successfully.
(170, 5)

,driver_id,total_deliveries,total_incidents,average_resolved_hours,incident_rate
0,D001,6,2,10.500,0.333
1,D002,7,4,14.025,0.571
2,D003,4,2,19.150,0.500
3,D004,9,5,5.960,0.556
4,D005,5,2,7.850,0.400

In [ ]:
# create hub performance summary dataset

hub_delivery_data = deliveries_clean.merge(
    hubs_clean,
    on="hub_id",
    how="left"
)

hub_performance_summary = hub_delivery_data.groupby(["hub_id", "hub_name", "zone", "hub_type"]).agg(
    total_deliveries=("delivery_id", "count"),
    average_route_distance_km=("route_distance_km", "mean"),
    average_route_overrides=("manual_route_override_count", "mean"),
    missing_proof_count=("proof_of_completion_missing", "sum"),
    average_customer_rating=("customer_rating_post_delivery", "mean"),
    total_fuel_or_charge_cost=("fuel_or_charge_cost", "sum")
).reset_index()

print("hub_performance_summary created successfully.")
print(hub_performance_summary.shape)
display(hub_performance_summary.head())

hub_performance_summary created successfully.
(8, 10)

,hub_id,hub_name,zone,hub_type,total_deliveries,average_route_distance_km,average_route_overrides,missing_proof_count,average_customer_rating,total_fuel_or_charge_cost
0,H01,North Exchange,North,Dispatch,136,13.643309,1.029412,6,3.842059,1734.79
1,H02,South Link,South,Dispatch,106,14.169151,0.915094,8,3.951792,1331.89
2,H03,East Dock,East,Warehouse,119,14.515546,0.890756,9,3.899496,1516.56
3,H04,West Gate,West,Dispatch,127,13.384567,0.874016,7,3.916457,1672.21
4,H05,Central Core,Central,Control,115,14.321652,0.947826,10,3.676000,1573.89

In [ ]:
# create a master analysis dataset by combining key operational data

complaint_order_summary = complaints_clean.groupby("order_id").agg(
    complaint_count=("complaint_id", "count"),
    average_resolution_days=("resolution_days", "mean"),
    total_compensation=("compensation_amount", "sum")
).reset_index()

incident_delivery_summary = incidents_clean.groupby("delivery_id").agg(
    incident_count=("incident_id", "count"),
    average_resolved_hours=("resolved_hours", "mean")
).reset_index()

northstar_master_analysis = orders_clean.merge(customers_clean, on="customer_id", how="left")
northstar_master_analysis = northstar_master_analysis.merge(deliveries_clean, on="order_id", how="left")
northstar_master_analysis = northstar_master_analysis.merge(hubs_clean, on="hub_id", how="left")
northstar_master_analysis = northstar_master_analysis.merge(vehicles_clean, on="vehicle_id", how="left")
northstar_master_analysis = northstar_master_analysis.merge(complaint_order_summary, on="order_id", how="left")
northstar_master_analysis = northstar_master_analysis.merge(incident_delivery_summary, on="delivery_id", how="left")

northstar_master_analysis["complaint_count"] = northstar_master_analysis["complaint_count"].fillna(0)
northstar_master_analysis["incident_count"] = northstar_master_analysis["incident_count"].fillna(0)
northstar_master_analysis["total_compensation"] = northstar_master_analysis["total_compensation"].fillna(0)

print("northstar_master_analysis created successfully.")
print(northstar_master_analysis.shape)
display(northstar_master_analysis.head())

northstar_master_analysis created successfully.
(1250, 47)

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status,delivery_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost,hub_name,zone,hub_type,capacity_score,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version,complaint_count,average_resolution_days,total_compensation,incident_count,average_resolved_hours
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0,24,South,Consumer,2025-03-02 11:24:00,73.2,57.9,App,Active,DL00937,D047,V090,H01,2024-08-20 16:29:00,2024-08-20 18:52:56.172161,OnTime,26.65,2.0,0.0,4.29,15.82,North Exchange,North,Dispatch,82.0,Hybrid,West,2024-08-16 01:10:00,93.80,98472.0,InRepair,v2.0,0.0,NaN,0.00,0.0,NaN
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,Airport,Low,109.30,App,0,20,West,Consumer,2024-09-23 21:00:00,56.1,62.6,App,Dormant,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,0.0,NaN,0.00,0.0,NaN
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,Airport,High,33.50,Phone,0,42,North,Consumer,2024-06-07 22:41:00,87.1,36.6,App,Active,DL00925,D041,V100,H02,2025-09-02 16:59:00,2025-09-03 01:50:39.644673,Delayed,13.04,2.0,0.0,3.70,13.16,South Link,South,Dispatch,78.0,CargoVan,East,2024-06-23 11:24:00,60.10,31876.0,Active,v2.0,1.0,2.0,8.66,0.0,NaN
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,Riverside,North,Medium,10.04,App,1,50,North,Consumer,2025-04-21 07:28:00,53.6,80.4,Partner API,Active,DL00002,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1.0,0.0,5.00,13.41,South Link,South,Dispatch,78.0,Diesel,Airport,2025-09-17 08:52:00,68.60,78468.0,Active,v2.2,0.0,NaN,0.00,0.0,NaN
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,South,Low,125.58,Phone,0,23,South,Consumer,2024-06-29 19:47:00,64.3,38.5,Phone,Active,DL00671,D054,V073,H03,2025-02-17 20:23:00,2025-02-18 08:05:00.047082,OnTime,16.01,1.0,0.0,4.38,13.53,East Dock,East,Warehouse,74.0,Hybrid,Airport,2024-05-28 05:33:00,78.05,191353.0,Active,v2.1,1.0,8.0,54.41,0.0,NaN

## Exporting Cleaned and Processed Datasets

The cleaned and generated analytical datasets are exported as CSV files. These files should then be posted to the 'datasets/cleaned/' subdirectory of the GitHub repository. Exporting the cleaned datasets makes it easier to finish subsequent coursework portions because SQL in R, Python analytics, and MongoDB Atlas implementation may all use the same prepared files

In [ ]:
# create a folder in Colab to store cleaned dataset files

import os

cleaned_folder = "/content/cleaned_datasets"
os.makedirs(cleaned_folder, exist_ok=True)

print("Cleaned dataset folder created successfully.")

Cleaned dataset folder created successfully.

In [ ]:
# export cleaned individual datasets

app_events_clean.to_csv(f"{cleaned_folder}/cleaned_app_events.csv", index=False)
complaints_clean.to_csv(f"{cleaned_folder}/cleaned_complaints.csv", index=False)
customers_clean.to_csv(f"{cleaned_folder}/cleaned_customers.csv", index=False)
deliveries_clean.to_csv(f"{cleaned_folder}/cleaned_deliveries.csv", index=False)
drivers_clean.to_csv(f"{cleaned_folder}/cleaned_drivers.csv", index=False)
hubs_clean.to_csv(f"{cleaned_folder}/cleaned_hubs.csv", index=False)
incidents_clean.to_csv(f"{cleaned_folder}/cleaned_incidents.csv", index=False)
orders_clean.to_csv(f"{cleaned_folder}/cleaned_orders.csv", index=False)
vehicles_clean.to_csv(f"{cleaned_folder}/cleaned_vehicles.csv", index=False)

# export derived and integrated datasets

integrated_orders_deliveries.to_csv(f"{cleaned_folder}/integrated_orders_deliveries.csv", index=False)
customer_complaint_summary.to_csv(f"{cleaned_folder}/customer_complaint_summary.csv", index=False)
driver_incident_summary.to_csv(f"{cleaned_folder}/driver_incident_summary.csv", index=False)
hub_performance_summary.to_csv(f"{cleaned_folder}/hub_performance_summary.csv", index=False)
northstar_master_analysis.to_csv(f"{cleaned_folder}/northstar_master_analysis.csv", index=False)

print("All cleaned and processed datasets exported successfully.")

All cleaned and processed datasets exported successfully.

In [ ]:
# list exported files

exported_files = os.listdir(cleaned_folder)

print("Exported cleaned dataset files:")
for file in exported_files:
    print(file)

Exported cleaned dataset files:
customer_complaint_summary.csv
hub_performance_summary.csv
driver_incident_summary.csv
northstar_master_analysis.csv
cleaned_app_events.csv
cleaned_vehicles.csv
cleaned_drivers.csv
cleaned_customers.csv
cleaned_complaints.csv
integrated_orders_deliveries.csv
cleaned_orders.csv
cleaned_incidents.csv
cleaned_hubs.csv
cleaned_deliveries.csv

In [ ]:
# create a zip file containing all cleaned datasets for download

import shutil

zip_path = "/content/northstar_cleaned_datasets"
shutil.make_archive(zip_path, "zip", cleaned_folder)

print("ZIP file created successfully:")
print(zip_path + ".zip")

ZIP file created successfully:
/content/northstar_cleaned_datasets.zip

In [ ]:
# download the cleaned datasets ZIP file

from google.colab import files

files.download("/content/northstar_cleaned_datasets.zip")